apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-monitor
  template:
    metadata:
      labels:
        app: container-monitor
    spec:
      serviceAccountName: monitor-sa
      containers:
        - name: monitor
          image: container-monitor:latest
          imagePullPolicy: Never
